<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<RootNamespace>Bitai.WebApi</RootNamespace>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<Version>10.0.1</Version>
        <AssemblyVersion>10.0.1</AssemblyVersion>
        <FileVersion>10.0.1</FileVersion>
		<Authors>Viko Bastidas (BITAI)</Authors>
		<Company>BITAI</Company>
		<Product>BITAI Web Api Helpers</Product>
		<Description>ASP NET. Web API Helpers</Description>		
		<Copyright>© 2026 BITAI Web API Helpers. MIT License.</Copyright>
		<PackageId>Bitai.WebApi.Helpers</PackageId>
		<RepositoryUrl>https://github.com/bitai-cs/WebApi.Helpers</RepositoryUrl>
		<PackageProjectUrl>https://github.com/bitai-cs/WebApi.Helpers</PackageProjectUrl>
		<PackageIcon>api_64.png</PackageIcon>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<RepositoryType>git</RepositoryType>
		<PackageTags>api;web;helpers;security;serialization</PackageTags>
		<PackageReleaseNotes>.NET 10 ready</PackageReleaseNotes>
		<PackageLicenseFile>LICENSE.md</PackageLicenseFile>
		<PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Duende.IdentityModel" Version="8.1.0" />		
	</ItemGroup>

	<ItemGroup>
		<None Include="..\..\LICENSE.md">
		  <Pack>True</Pack>
		  <PackagePath>\</PackagePath>
		</None>
		<None Include="..\..\README.md">
		  <Pack>True</Pack>
		  <PackagePath>\</PackagePath>
		</None>
		<None Include="..\..\resources\api_64.png">
			<Pack>True</Pack>
			<PackagePath></PackagePath>
		</None>
	</ItemGroup>

</Project>
